### ISSUE TITLE
[REQ] \e\ and Colab autobuilder

### ISSUE THREAD

**Issue by MarcoRavich** [TeamExyKings/-android_device_samsung_jackpot2lte#1]
Hi there,
it would be great to have an [\e\ (aka deGoogled-Lineage)](https://e.foundation/) official build for jackpot2lte (and jackpotlte) too.

Some time ago, someone opened a request 3ad @ [\e\ community](https://community.e.foundation/) for this device that we "bumped" by linking device's GH (re)sources:

https://community.e.foundation/t/samsung-galaxy-a8-2018/22646

If you need, here's a couple of interesting guides that may help to build it:
https://doc.e.foundation/support-topics/build-e
https://community.e.foundation/t/howto-building-e-roms-a-beginners-guide/26371

Last but not least, we've also suggested (check [here](https://community.e.foundation/t/automated-builds-v-machine/43336)) to setup a "build (V)Machine" by modding these colab notebooks to made them device agnostic:
https://github.com/viam1-dev/colab_lineage_build
https://github.com/T110-android/colab_build

Hope can "inspire" you.

Thanks in advance.

**Comment by Griffin98** [comment]
We no longer support these(or any) devices. You can use our repos as a starting point to build the ROM and fix it. However, you cannot expect any technical support from us. Happy tweaking!

**Comment by MarcoRavich** [comment]
Thanks for your reply.

Seems that GSI is actually the "best way to go"...

Anyway, if you like coding and the "build (V)Machine" idea, check out above links (someone may need help)...
